### ISSUE TITLE
Error in ffbase

### ISSUE THREAD

**Issue by kmkostka** [ABMI/MddAfterBbVal#1]
Starting Prediction  2020-11-01 21:47:41 for  883198  people
Error: Error in ffbase::ffmatch(covariates$rowId, rowIds): inherits(x, "ff_vector") & inherits(table, "ff_vector") is not TRUE.

What version of the PLP library should we be using?

**Comment by jshsh7553** [comment]
Sorry for the inconvenience.

The latest version of the PatientLevelPrediction package no more uses the ff package,
so does the validation package generated from the latest PLP package.

Please update the PLP package to the latest version which is v4.0.5.

This is github page of PatientLevelPrediction.
https://github.com/OHDSI/PatientLevelPrediction

And this it the latest installation guide.
https://github.com/OHDSI/PatientLevelPrediction/blob/master/inst/doc/InstallationGuide.pdf

Thanks.

**Comment by chandryou** [comment]
@kmkostka 

I've updated the rEnviornment which was used in this package in this commit: 

https://github.com/ohdsi-studies/MddAfterBbValidation/commit/b4ee0dcec6253b8b06cdda3b5e3f598b5313256f
